//
//  ContentView.swift
//  NINEMUSES
//
//  Created by Petie Positivo on 6/21/23.
//  Generated by ChatGPT
//

import SwiftUI

struct ContentView: View {
    @StateObject private var viewModel: ContentViewModel

    init(viewModel: ContentViewModel) {
        self._viewModel = StateObject(wrappedValue: viewModel)
    }

    var body: some View {
        NavigationView {
            VStack {
                if viewModel.isAuthenticated {
                    LikedSongsView(viewModel: viewModel.likedSongsViewModel)
                } else {
                    AuthenticationView(viewModel: viewModel.authenticationViewModel)
                }
            }
            .navigationBarTitle("NINEMUSES")
        }
        .onAppear {
            viewModel.onViewAppear()
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
