//
//  AuthenticationState.swift
//  NINEMUSES
//
//  Created by Petie Positivo on 6/21/23.
//  GENERATED BY CHATGPT
//

import Foundation
import ComposableArchitecture

struct AuthenticationState: Equatable {
    var isLoggedIn: Bool = false
}

enum AuthenticationAction {
    case logIn
    case logOut
    case loggedIn
    case loggedOut
}

let authenticationReducer = Reducer<AuthenticationState, AuthenticationAction, AppEnvironment> { state, action, _ in
    switch action {
    case .logIn:
        // Implement the logic to authenticate the user
        state.isLoggedIn = true
        return .none
    case .logOut:
        // Implement the logic to log out the user
        state.isLoggedIn = false
        return .none
    case .loggedIn:
        // Perform any necessary actions after successful login
        return .none
    case .loggedOut:
        // Perform any necessary actions after logout
        return .none
    }
}
