//
//  AuthenticationEnvironment.swift
//  NINEMUSES
//
//  Created by Petie Positivo on 6/22/23.
//  Generated by ChatGPT
//

import Foundation
import ComposableArchitecture

struct AuthenticationEnvironment {
    let authenticationService: AuthenticationService
    // Add any other dependencies or services required for authentication.
}
