//
//  AuthenticationView.swift
//  NINEMUSES
//
//  Created by Petie Positivo on 6/22/23.
//  Generated by ChatGPT
//

import Foundation
import SwiftUI
import SpotifyiOS

struct AuthenticationView: View {
    @State private var isPresentingSpotifyAuth = false
    @Environment(\.presentationMode) var presentationMode

    var body: some View {
        VStack {
            Text("Welcome to Your App")
                .font(.title)
                .padding()
            
            Button(action: {
                isPresentingSpotifyAuth = true
            }) {
                Text("Sign in with Spotify")
                    .font(.headline)
                    .foregroundColor(.white)
                    .padding()
                    .background(Color.green)
                    .cornerRadius(8)
            }
        }
        .sheet(isPresented: $isPresentingSpotifyAuth) {
            SpotifyAuthenticatorView(
                isPresented: $isPresentingSpotifyAuth,
                onCompletion: handleAuthenticationResult
            )
        }
    }

    func handleAuthenticationResult(result: Result<SpotifyAccessToken, Error>) {
        switch result {
        case .success(let accessToken):
            // Handle successful authentication, e.g., save the access token
            
            // Dismiss the authentication view
            presentationMode.wrappedValue.dismiss()
            
        case .failure(let error):
            // Handle authentication error, e.g., show an error message
            print("Authentication error: \(error.localizedDescription)")
        }
    }
}
