//
//  Constants.swift
//  NINEMUSES
//
//  Created by Petie Positivo on 6/22/23.
//  Generated by ChatGPT
//

import Foundation

struct Constants {
    // Spotify API Constants
    static let spotifyAPIBaseUrl = "https://api.spotify.com/v1"
    static let spotifyClientID = "YOUR_SPOTIFY_CLIENT_ID"
    static let spotifyClientSecret = "YOUR_SPOTIFY_CLIENT_SECRET"
    static let spotifyRedirectUri = "YOUR_SPOTIFY_REDIRECT_URI"
    
    // Spotify API Endpoints
    static let spotifyTokenEndpoint = "https://accounts.spotify.com/api/token"
    static let spotifyRecentlyPlayedEndpoint = "/me/player/recently-played"
}

