//
//  ContentView.swift
//  NINEMUSES
//
//  Created by Petie Positivo on 6/22/23.
//  Generated by ChatGPT
//

import Foundation
import SwiftUI

struct ContentView: View {
    
    var body: some View {
        NavigationView {
            Text("sad")
        }
    }
}

struct SongRowView: View {
    let song: Song
    
    var body: some View {
        HStack {
            // Display song details, such as album artwork, name, artist, etc.
        }
    }
}
