//
//  ContentView.swift
//  NINEMUSES
//
//  Created by Petie Positivo on 6/21/23.
//  Generated by ChatGPT
//

import SwiftUI
import ComposableArchitecture

struct ContentView: View {
    let store: Store<AppState, AppAction>
    @ObservedObject var viewStore: ViewStore<AppState, AppAction>

    var body: some View {
        NavigationView {
            WithViewStore(store) { viewStore in
            VStack {
                if viewStore.isAuthenticated {
                    LikedSongsView(store: store.scope(state: { $0.likedSongs }, action: AppAction.likedSongs))
                } else {
                    AuthenticationView(store: store.scope(state: { $0.authentication }, action: AppAction.authentication))
                }
            }
            .navigationBarTitle("NINEMUSES")
        }
    }
        .onAppear {
            viewStore.send(.authentication(.logIn))
        }
    }
}

struct AuthenticationView: View {
    let store: Store<AuthenticationState, AuthenticationAction>
    @ObservedObject var viewStore: ViewStore<AuthenticationState, AuthenticationAction>

    var body: some View {
        VStack {
            Text("Welcome to NINEMUSES!")
                .font(.title)
                .padding()
            
            if viewStore.isLoggedIn {
                Button(action: { viewStore.send(.logOut) }) {
                    Text("Log Out")
                        .font(.headline)
                        .padding()
                }
            } else {
                Button(action: { viewStore.send(.logIn) }) {
                    Text("Log In")
                        .font(.headline)
                        .padding()
                }
            }
        }
    }
}

struct LikedSongsView: View {
    let store: Store<LikedSongsState, LikedSongsAction>

    var body: some View {
        WithViewStore(store) { viewStore in
                   List(viewStore.songs, id: \.self) { song in
                       Button(action: { viewStore.send(.selectSong(song)) }) {
                           Text(song.title)
                       }
                   }
               }
    }
}
