//
//  Models.swift
//  NINEMUSES
//
//  Created by Petie Positivo on 6/22/23.
//  Generated by ChatGPT
//

import Foundation

struct Song: Identifiable {
    let id: String
    let name: String
    let artist: String
    let album: String
    let imageURL: URL
    let playedDate: Date
}
