//
//  RecentlyPlayedView.swift
//  NINEMUSES
//
//  Created by Petie Positivo on 6/22/23.
//  Generated by ChatGPT
//

import Foundation
import SwiftUI

struct RecentlyPlayedView: View {
    @StateObject private var viewModel = RecentlyPlayedViewModel()

    var body: some View {
        VStack {
            if viewModel.isLoading {
                ProgressView()
            } else if let songs = viewModel.recentlyPlayedSongs {
                List(songs) { song in
                    SongRowView(song: song)
                }
            } else if let error = viewModel.error {
                Text("Error: \(error.localizedDescription)")
            } else {
                Text("No recently played songs.")
            }
        }
        .onAppear {
            viewModel.fetchRecentlyPlayedSongs()
        }
        .navigationTitle("Recently Played")
    }
}

struct SongRowView: View {
    let song: Song
    
    var body: some View {
        HStack {
            // Display song details, such as album artwork, name, artist, etc.
        }
    }
}
