//
//  SpotifyService.swift
//  NINEMUSES
//
//  Created by Petie Positivo on 6/22/23.
//  Generated by ChatGPT
//

import Foundation
import Combine

struct SpotifyService {
    func fetchLikedSongs() -> AnyPublisher<Result<[Song], Error>, Never> {
        // Implement the logic to fetch liked songs from Spotify API
        // and return a publisher with the result
        fatalError("Not implemented")
    }
}
